### ISSUE TITLE
toughts on nats

### ISSUE THREAD

**Issue by SunChero** [nicolasparada/nakama#2]
Hi Nicolas ,
 i saw you moved from using the nats to vice ..etc.
would be nice if you could share your experience working with nats and vice ... is it worth  the effort .. im actually planning on using nats extensively on one of my pet projects

thanks a lot

**Comment by nicolasparada** [comment]
Sure. Right now, all realtime capabilities cannot escale. Because the subscriptions happens in memory.
Lets put it this way. Lets say we escale the server by running multiple instances on a load balancer, lets say 2 instances. OK.
Then there is user0, which has two followers: user1 and user2.
User1 is subscribing to the timeline on one server, but user2 is subscribed on the other server. When user0 publishes a post, it won't be broadcasted to both of these users, only to the one that is on the same server that user0.
That's why we need to move the "transport" we use to broadcast the notifications. We need to move it outside of the Go server code, to it's own service so it can be shared (on escaled by itself also). There comes NATS 🙂

You are right, I was playing with NATS, but I didn't record it for the [youtube series](https://www.youtube.com/playlist?list=PLOzDrFftjC0-yDkIIllvqRHJ_5XyIPxI4) so I reverted the changes. I do plan to record it.

**Comment by SunChero** [comment]
Ok, thanks :)
